const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Arr,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Arr.Acts.Pop,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutEnd
	];
};
self.C3_JsPropNameTable = [
	{Sine: 0},
	{btnBasla: 0},
	{btnBilgi: 0},
	{btnButon: 0},
	{kapla: 0},
	{btnFullScreen: 0},
	{btnHazirlayanlar: 0},
	{btnHome: 0},
	{btnKapat: 0},
	{btnKaynakca: 0},
	{durum: 0},
	{btnMuzik: 0},
	{btnSes: 0},
	{btnTekrarOyna: 0},
	{a: 0},
	{bar: 0},
	{Touch: 0},
	{Mouse: 0},
	{Audio: 0},
	{Browser: 0},
	{gameBackground: 0},
	{sorular: 0},
	{btndogru: 0},
	{btnyanlis: 0},
	{sorudiz: 0},
	{background: 0},
	{hazirlayanlar: 0},
	{kaynakca: 0},
	{bilgi: 0},
	{butonlarr: 0},
	{end: 0},
	{pilbari: 0},
	{Flash: 0},
	{DY: 0},
	{DY2: 0},
	{Sprite: 0},
	{butonlar: 0},
	{barr: 0},
	{randomsoru: 0},
	{dogru_sayisi: 0},
	{tiklandi: 0}
];

self.InstanceType = {
	btnBasla: class extends self.ISpriteInstance {},
	btnBilgi: class extends self.ISpriteInstance {},
	btnButon: class extends self.ISpriteInstance {},
	btnFullScreen: class extends self.ISpriteInstance {},
	btnHazirlayanlar: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	btnKapat: class extends self.ISpriteInstance {},
	btnKaynakca: class extends self.ISpriteInstance {},
	btnMuzik: class extends self.ISpriteInstance {},
	btnSes: class extends self.ISpriteInstance {},
	btnTekrarOyna: class extends self.ISpriteInstance {},
	bar: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	gameBackground: class extends self.ISpriteInstance {},
	sorular: class extends self.ISpriteInstance {},
	btndogru: class extends self.ISpriteInstance {},
	btnyanlis: class extends self.ISpriteInstance {},
	sorudiz: class extends self.IArrayInstance {},
	background: class extends self.ISpriteInstance {},
	hazirlayanlar: class extends self.ISpriteInstance {},
	kaynakca: class extends self.ISpriteInstance {},
	bilgi: class extends self.ISpriteInstance {},
	butonlarr: class extends self.ISpriteInstance {},
	end: class extends self.ISpriteInstance {},
	pilbari: class extends self.ISpriteInstance {},
	DY: class extends self.ISpriteInstance {},
	DY2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	butonlar: class extends self.ISpriteInstance {},
	barr: class extends self.ISpriteInstance {}
}